# GitLab CI configuration to use SSH and docker registry
#
# Prerequisities:
# 1. Generate a password less SSH key on a local machine
# 2. Add the public key as a deploy key to the repository/group
# 3. Add the private key as a variable (e.g. SSH_KEY_PRIVATE) to the repository/group

image: docker:19.03.1

services:
  - docker:19.03.1-dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"

before_script:
  - 'which ssh-agent || ( apk --update add openssh-client git )'
  - eval $(ssh-agent -s)
  - echo "$CI_SSH_KEY_PRIVATE" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

build_image:
  script:
    - ci/build-docker-image.sh --ssh --image="$CI_REGISTRY/avular/common-tools/package-manager/tue-env" --branch="$CI_COMMIT_BRANCH" --commit="$CI_COMMIT_SHA" --pull_request=${CI_MERGE_REQUEST_ID:-"false"} --pull_request_branch="$CI_MERGE_REQUEST_BRANCH_NAME" --user="gitlab-ci-token" --password="$CI_JOB_TOKEN" --registry="$CI_REGISTRY"
