os: linux
dist: xenial
language: shell

jobs:
  include:
    - stage: Linting
      name: shellcheck
      script: bash -c 'shopt -s globstar; shellcheck **/*.bash **/*.sh'

    - &docker-generation
      stage: Docker generation
      language: generic
      name: tue-env
      before_install: ci/update-docker.bash
      script: ci/build-docker-image.sh --image="tuerobotics/$TRAVIS_JOB_NAME" --branch="$TRAVIS_BRANCH" --commit="$TRAVIS_COMMIT" --pull_request="$TRAVIS_PULL_REQUEST" --pull_request_branch="$TRAVIS_PULL_REQUEST_BRANCH" --user="$DOCKER_HUB_USERNAME" --password="$DOCKER_HUB_PASSWORD"

    - <<: *docker-generation
      name: tue-env-cuda
      if: branch = master
