os: linux
dist: xenial
language: shell

jobs:
  include:
    - stage: Linting
      name: shellcheck
      script: bash -c 'shopt -s globstar; shellcheck **/*.bash **/*.sh'
    - &docker-generation
      stage: Docker generation
      language: generic
      services: docker
      name: tue-env
      script: ci/build-docker-image.sh -i="tuerobotics/tue-env" -b="$TRAVIS_BRANCH" -c="$TRAVIS_COMMIT" -pr="$TRAVIS_PULL_REQUEST" -prb="$TRAVIS_PULL_REQUEST_BRANCH" -u="$DOCKER_HUB_USERNAME" -p="$DOCKER_HUB_PASSWORD" -r=""
    - <<: *docker-generation
      name: tue-env-cuda
      script: ci/build-docker-image.sh -i="tuerobotics/tue-env-cuda" -b="$TRAVIS_BRANCH" -c="$TRAVIS_COMMIT" -pr="$TRAVIS_PULL_REQUEST" -prb="$TRAVIS_PULL_REQUEST_BRANCH" -u="$DOCKER_HUB_USERNAME" -p="$DOCKER_HUB_PASSWORD" -r=""
