os: linux
dist: xenial
language: shell

jobs:
  include:
    - stage: Linting
      name: shellcheck
      script: bash -c 'shopt -s globstar; shellcheck **/*.bash **/*.sh'

    - &docker-generation
      stage: Docker generation
      language: generic
      name: tue-env
      before_install:
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
        - sudo rm /etc/docker/daemon.json
        - sudo systemctl restart docker

      script: ci/build-docker-image.sh --image="tuerobotics/tue-env" --branch="$TRAVIS_BRANCH" --commit="$TRAVIS_COMMIT" --pull_request="$TRAVIS_PULL_REQUEST" --pull_request_branch="$TRAVIS_PULL_REQUEST_BRANCH" --user="$DOCKER_HUB_USERNAME" --password="$DOCKER_HUB_PASSWORD"

    - <<: *docker-generation
      name: tue-env-cuda
      script: ci/build-docker-image.sh --image="tuerobotics/tue-env-cuda" --branch="$TRAVIS_BRANCH" --commit="$TRAVIS_COMMIT" --pull_request="$TRAVIS_PULL_REQUEST" --pull_request_branch="$TRAVIS_PULL_REQUEST_BRANCH" --user="$DOCKER_HUB_USERNAME" --password="$DOCKER_HUB_PASSWORD"
