name: 'Commit range'
description: 'Determine commit range'
outputs:
  commit-range:
    description: 'Range of commits in this run'
    value: ${{ steps.commit-range.outputs.commit-range }}
runs:
  using: "composite"
  steps:
    - name: Commit range
      id: commit-range
      env:
        commit_list: ${{ toJson(github.event.commits) }} # Doing this inside run doesn't work because of piping
      run: |
        if [ "${GITHUB_EVENT_NAME}" == "push" ]
        then
          COMMIT_RANGE=${{ github.event.compare }}
          if [[ "${COMMIT_RANGE}" == *"..."* ]] && [[ $(echo "${commit_list}" | jq '. | length') > 1 ]]
          then
            COMMIT_RANGE=${COMMIT_RANGE#https://github.com/${{ github.repository }}/compare/}
          else
            COMMIT_RANGE=""
          fi
        elif [ "${GITHUB_EVENT_NAME}" == "pull_request" ]
        then
          OLDEST=${{ github.event.pull_request.base.sha }}
          NEWEST=${{ github.event.pull_request.head.sha }}
          COMMIT_RANGE="${OLDEST}...${NEWEST}"
        fi
        echo -e "\e[35m\e[1m COMMIT_RANGE = ${COMMIT_RANGE} \e[0m"
        echo "::set-output name=commit-range::${COMMIT_RANGE}"
      shell: bash
