name: Docker Tags

on: delete

jobs:
  delete_docker_tags:
    name: Deleting docker tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Script
        run: python3 ci/delete-docker-tags.py --org "tuerobotics" --image "tue-env-ros-noetic" "tue-env-ros-galactic" "tue-env-ros-humble" -t "${{ github.event.ref }}-amd64" --username "${{ secrets.DOCKER_HUB_USERNAME }}" --password "${{ secrets.DOCKER_HUB_PASSWORD }}"
